package com.huyx;

import com.huyx.entity.User;
import com.huyx.repository.UserRepository;
import com.huyx.repository.UserRepositoryP;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;

@RunWith(SpringRunner.class)
@SpringBootTest
public class SpringBootDemoApplicationTests {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private UserRepositoryP userRepositoryP;

	@Test
	public void contextLoadsUserRepository() {
		List<User> users=userRepository.findByNameContains("i");
		for (User user:users){
			System.out.println(user.getEmail());
		}
	}

	@Test
	public void contextLoadsUserRepositoryP() {
		Iterable<User> users=userRepositoryP.findAll();
		for (User user:users){
			System.out.println(user.getEmail());
		}
	}

}
